name: Setup asc
description: Install the asc CLI (App Store Connect CLI) in GitHub Actions.
author: Rudrank Riyam

inputs:
  version:
    description: "Version to install: latest, 0.28.12, v0.28.12, or main"
    required: false
    default: latest
  cache:
    description: "Cache the downloaded release asset (true/false)"
    required: false
    default: "true"
  install-dir:
    description: "Directory to install asc into (defaults to $RUNNER_TEMP/asc/bin)"
    required: false
  token:
    description: "GitHub token for API requests (avoids rate limits when resolving latest)"
    required: false
    default: ${{ github.token }}

outputs:
  asc-path:
    description: Absolute path to the installed asc binary
    value: ${{ steps.install.outputs.asc-path }}
  asc-version:
    description: Resolved version that was installed
    value: ${{ steps.resolve.outputs.version }}
  cache-hit:
    description: Whether the binary was restored from cache
    value: ${{ steps.cache.outputs.cache-hit }}

runs:
  using: composite
  steps:
    - name: Resolve version and platform
      id: resolve
      shell: bash
      run: |
        set -euo pipefail

        REPO="rudrankriyam/App-Store-Connect-CLI"

        INPUT_VERSION="${{ inputs.version }}"
        # Strip leading 'v' so both v0.28.12 and 0.28.12 work
        INPUT_VERSION="${INPUT_VERSION#v}"

        case "${RUNNER_OS}" in
          Linux)   OS="linux" ;;
          macOS)   OS="macOS" ;;
          Windows) OS="windows" ;;
          *)
            echo "::error::Unsupported runner OS: ${RUNNER_OS}"
            exit 1
            ;;
        esac

        case "${RUNNER_ARCH}" in
          X64)   ARCH="amd64" ;;
          ARM64) ARCH="arm64" ;;
          *)
            echo "::error::Unsupported runner arch: ${RUNNER_ARCH}"
            exit 1
            ;;
        esac

        VERSION="${INPUT_VERSION}"
        MODE="release"

        if [ -z "${INPUT_VERSION}" ] || [ "${INPUT_VERSION}" = "latest" ]; then
          echo "::group::Resolving latest version"
          LATEST_URL="$(curl -fsSL -o /dev/null -w "%{url_effective}" \
            -H "Authorization: token ${{ inputs.token }}" \
            "https://github.com/${REPO}/releases/latest")"
          VERSION="${LATEST_URL##*/}"
          if [ -z "${VERSION}" ] || [ "${VERSION}" = "latest" ]; then
            echo "::error::Could not determine latest version"
            exit 1
          fi
          echo "Resolved latest: ${VERSION}"
          echo "::endgroup::"
        elif [ "${INPUT_VERSION}" = "main" ]; then
          MODE="go"
          VERSION="main"
        fi

        echo "mode=${MODE}" >> "${GITHUB_OUTPUT}"
        echo "version=${VERSION}" >> "${GITHUB_OUTPUT}"
        echo "os=${OS}" >> "${GITHUB_OUTPUT}"
        echo "arch=${ARCH}" >> "${GITHUB_OUTPUT}"

        if [ "${MODE}" = "release" ]; then
          ASSET="asc_${VERSION}_${OS}_${ARCH}"
          BIN_NAME="asc"
          if [ "${OS}" = "windows" ]; then
            ASSET="${ASSET}.exe"
            BIN_NAME="asc.exe"
          fi

          BASE_URL="https://github.com/${REPO}/releases/download/${VERSION}"
          echo "asset=${ASSET}" >> "${GITHUB_OUTPUT}"
          echo "bin-name=${BIN_NAME}" >> "${GITHUB_OUTPUT}"
          echo "bin-url=${BASE_URL}/${ASSET}" >> "${GITHUB_OUTPUT}"
          echo "checksums-url=${BASE_URL}/asc_${VERSION}_checksums.txt" >> "${GITHUB_OUTPUT}"
        fi

        echo "::notice::Installing asc ${VERSION} (${OS}/${ARCH}, mode=${MODE})"

    - name: Restore cached binary
      id: cache
      if: ${{ steps.resolve.outputs.mode == 'release' && inputs.cache == 'true' }}
      uses: actions/cache@v4
      with:
        path: ${{ runner.temp }}/setup-asc-cache
        key: setup-asc-${{ steps.resolve.outputs.version }}-${{ runner.os }}-${{ runner.arch }}

    - name: Download release binary
      id: download
      if: ${{ steps.resolve.outputs.mode == 'release' }}
      shell: bash
      run: |
        set -euo pipefail
        echo "::group::Download"

        CACHE_ROOT="${RUNNER_TEMP}/setup-asc-cache"
        DOWNLOAD_DIR="${CACHE_ROOT}/${{ steps.resolve.outputs.version }}/${{ steps.resolve.outputs.os }}-${{ steps.resolve.outputs.arch }}"
        mkdir -p "${DOWNLOAD_DIR}"

        ASSET="${{ steps.resolve.outputs.asset }}"
        BIN_URL="${{ steps.resolve.outputs.bin-url }}"
        CHECKSUMS_URL="${{ steps.resolve.outputs.checksums-url }}"

        if [ -f "${DOWNLOAD_DIR}/${ASSET}" ]; then
          echo "Using cached ${ASSET}"
        else
          echo "Downloading ${ASSET}..."
          curl -fsSL "${BIN_URL}" -o "${DOWNLOAD_DIR}/${ASSET}"
        fi

        if [ ! -f "${DOWNLOAD_DIR}/checksums.txt" ]; then
          curl -fsSL "${CHECKSUMS_URL}" -o "${DOWNLOAD_DIR}/checksums.txt"
        fi

        echo "download-dir=${DOWNLOAD_DIR}" >> "${GITHUB_OUTPUT}"
        echo "::endgroup::"

    - name: Verify SHA-256 checksum
      if: ${{ steps.resolve.outputs.mode == 'release' }}
      shell: bash
      run: |
        set -euo pipefail
        echo "::group::Verify checksum"

        DIR="${{ steps.download.outputs.download-dir }}"
        ASSET="${{ steps.resolve.outputs.asset }}"
        FILE="${DIR}/${ASSET}"
        CHECKSUMS="${DIR}/checksums.txt"

        EXPECTED="$(grep -E "[ *]${ASSET}$" "${CHECKSUMS}" | awk '{print $1}')"
        if [ -z "${EXPECTED}" ]; then
          echo "::error::Checksum for ${ASSET} not found in checksums.txt"
          exit 1
        fi

        if command -v shasum >/dev/null 2>&1; then
          ACTUAL="$(shasum -a 256 "${FILE}" | awk '{print $1}')"
        elif command -v sha256sum >/dev/null 2>&1; then
          ACTUAL="$(sha256sum "${FILE}" | awk '{print $1}')"
        else
          echo "::warning::No checksum tool available (shasum/sha256sum). Skipping verification."
          echo "::endgroup::"
          exit 0
        fi

        if [ "${EXPECTED}" != "${ACTUAL}" ]; then
          echo "::error::Checksum verification failed. Expected ${EXPECTED}, got ${ACTUAL}"
          exit 1
        fi

        echo "Checksum verified: ${ACTUAL}"
        echo "::endgroup::"

    - name: Setup Go (main branch install)
      if: ${{ steps.resolve.outputs.mode == 'go' }}
      uses: actions/setup-go@v5
      with:
        go-version: stable

    - name: Install asc
      id: install
      shell: bash
      run: |
        set -euo pipefail
        echo "::group::Install"

        INSTALL_DIR="${{ inputs.install-dir }}"
        if [ -z "${INSTALL_DIR}" ]; then
          INSTALL_DIR="${RUNNER_TEMP}/asc/bin"
        fi
        mkdir -p "${INSTALL_DIR}"

        if [ "${{ steps.resolve.outputs.mode }}" = "go" ]; then
          GOBIN="${INSTALL_DIR}" go install github.com/rudrankriyam/App-Store-Connect-CLI@main
          BIN_PATH="${INSTALL_DIR}/asc"
        else
          DIR="${{ steps.download.outputs.download-dir }}"
          cp "${DIR}/${{ steps.resolve.outputs.asset }}" "${INSTALL_DIR}/${{ steps.resolve.outputs.bin-name }}"
          chmod +x "${INSTALL_DIR}/${{ steps.resolve.outputs.bin-name }}" || true
          BIN_PATH="${INSTALL_DIR}/${{ steps.resolve.outputs.bin-name }}"
        fi

        echo "${INSTALL_DIR}" >> "${GITHUB_PATH}"
        echo "asc-path=${BIN_PATH}" >> "${GITHUB_OUTPUT}"
        echo "Installed asc ${{ steps.resolve.outputs.version }} at ${BIN_PATH}"
        echo "::endgroup::"

branding:
  icon: terminal
  color: blue
